
import React from 'react';

const ProfilePage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-12 animate-fadeIn pb-20">
      <header className="text-center space-y-4">
        <div className="w-24 h-24 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-full mx-auto flex items-center justify-center text-white text-3xl font-black shadow-xl shadow-blue-200">
          JD
        </div>
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Career Readiness Certificate</h1>
          <p className="text-gray-500">Holistic skill profile generated by CareerPilot AI</p>
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <section className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm space-y-6">
          <h3 className="text-xl font-bold text-gray-900">Expertise Levels</h3>
          <div className="space-y-4">
            {['Software Architecture', 'Behavioral Leadership', 'Technical Communication', 'Problem Solving'].map(skill => (
              <div key={skill} className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-700 font-medium">{skill}</span>
                  <span className="text-blue-600 font-bold">Advanced</span>
                </div>
                <div className="w-full bg-gray-100 h-2 rounded-full overflow-hidden">
                  <div className="bg-blue-600 h-full w-[85%]"></div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="bg-white p-8 rounded-3xl border border-gray-100 shadow-sm space-y-6">
          <h3 className="text-xl font-bold text-gray-900">Recruiter Insights</h3>
          <ul className="space-y-4">
            <li className="flex gap-4">
              <div className="w-6 h-6 bg-green-100 text-green-600 rounded flex-shrink-0 flex items-center justify-center">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-sm text-gray-600">Strong "FAANG-style" technical depth detected in System Design rounds.</p>
            </li>
            <li className="flex gap-4">
              <div className="w-6 h-6 bg-green-100 text-green-600 rounded flex-shrink-0 flex items-center justify-center">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <p className="text-sm text-gray-600">Excellent cultural fit for high-growth startups; demonstrates adaptability.</p>
            </li>
            <li className="flex gap-4">
              <div className="w-6 h-6 bg-amber-100 text-amber-600 rounded flex-shrink-0 flex items-center justify-center">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                </svg>
              </div>
              <p className="text-sm text-gray-600">Consider refining "STAR" structure for behavioral questions to hit 10/10.</p>
            </li>
          </ul>
        </section>
      </div>

      <div className="bg-blue-600 rounded-3xl p-10 text-center text-white space-y-4">
        <h2 className="text-2xl font-bold">Ready to take the next step?</h2>
        <p className="opacity-80">Our Public Interview API allows you to share your results with verified recruiters.</p>
        <button className="bg-white text-blue-600 px-8 py-3 rounded-2xl font-bold hover:bg-blue-50 transition-all">
          Generate Public Profile Link
        </button>
      </div>
    </div>
  );
};

export default ProfilePage;
